// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Anime Openings",
  description: "The best anime openings, in my humble opinion",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="w-100 bg-orange-300">
          <nav className="flex justify-center w-100">
            <Link
              className="m-1 text-emerald-500 hover:text-emerald-800"
              href="/"
            >
              Home
            </Link>
            <Link
              className="m-1 text-emerald-500 hover:text-emerald-800"
              href="/management"
            >
              Manage
            </Link>
            <Link
              className="m-1 text-emerald-500 hover:text-emerald-800"
              href="/about"
            >
              About
            </Link>
          </nav>
        </header>
        {children}
        <footer className="text-center">
          &copy; Ace Chianni Capstone 2024
        </footer>
      </body>
    </html>
  );
}
